### ISSUE TITLE
Why Similar to Imagizer ?

### ISSUE THREAD

**Issue by birajrai** [gifaldyazkaa/sena#4]
https://github.com/birajrai/Imagizer

**Comment by birajrai** [comment]
but you did better

**Comment by gifaldyazkaa** [comment]
yes. i used some parts of your code as reference here. what i'm using as a reference is the `*.ejs` code, and some small pieces of your `index.js`.

**Comment by birajrai** [comment]
okay sir 👾🕊️

**Comment by birajrai** [comment]
Will you please add this line in your sena Readme?
Not necessary but you can if you wants to give me some credits 🕊️✨
included in the main repo (https://github.com/birajrai/Imagizer)

**Comment by gifaldyazkaa** [comment]
sure. will be included in the next push.

**Comment by gifaldyazkaa** [comment]
re-opened #4. will be closed when done.

**Comment by gifaldyazkaa** [comment]
credits has been added into the project readme. this issue will be closed when there is an PR mentioning this issue.
![image](https://user-images.githubusercontent.com/68645946/191261499-b1fcf2d6-7e84-4367-8c3d-857963169086.png)

**Comment by gifaldyazkaa** [comment]
fixed this in #6. ready to closed.
